defimpl String.Chars, for: Apix.Schema.Ast.Meta do
  def to_string(meta) do
    module =
      if meta.module,
        do: meta.module,
        else: "<no module>"

    file =
      if meta.file,
        do: meta.file,
        else: "<no file>"

    line =
      if meta.line,
        do: ":#{meta.line}",
        else: ""

    generated_by =
      if meta.generated_by,
        do: " (generated by #{inspect meta.generated_by})",
        else: ""

    "#{module} at #{file}#{line}#{generated_by}"
  end
end
